name: ECS Deploy
description: Updates the manifest to a new image for ECS tasks
author: https://github.com/Joibel
requirements: []
configuration:
  properties:
    key:
      type: string
    label:
      type: string
    arn_role:
      type: string
    command:
      type: string
    depends_on:
      type: array
  additionalProperties: false
