#!/bin/bash

set -xeuo pipefail
function prefix_read_list() {
  local prefix="$1"
  local parameter="${prefix}_0"

  if [[ -n "${!parameter:-}" ]]; then
    local i=0
    local parameter="${prefix}_${i}"
    while [[ -n "${!parameter:-}" ]]; do
      echo "${!parameter}"
      i=$((i+1))
      parameter="${prefix}_${i}"
    done
  elif [[ -n "${!prefix:-}" ]]; then
    echo "${!prefix}"
  fi
}
DEPENDS_ON_LIST=$(prefix_read_list BUILDKITE_PLUGIN_ECS_DEPLOY_DEPENDS_ON)
if [[ -n "${DEPENDS_ON_LIST}" ]] ; then
   DEPENDS_ON="    depends_on:\n"
   for line in ${DEPENDS_ON_LIST} ; do
     DEPENDS_ON="$DEPENDS_ON     - $line\n"
   done
fi
export DEPENDS_ON
envsubst '${DEPENDS_ON}' <"$(dirname "${BASH_SOURCE}")/../ecs-deploy" | sed -e 's/\\n/\n/g' | buildkite-agent pipeline upload
